### ISSUE TITLE
Missing minimize button

### ISSUE THREAD

**Issue by hatran777** [ShatteredIcicle/firefox-ui-regression-mending#1]
--proton-tab-block-margin: 0px !important; /* Tabs should touch the bar */

under photon-tabs.css removes the minimize button or causes it to be transparent. This was shown on Windows 10.

**Comment by ShatteredIcicle** [comment]
Hey, thanks for you report 🙂 .

However I'm not able to reproduce on a fresh latest Nightly profile.
**Are you using special themes or other userChrome changes?**

My thoughts are that I may be misunderstanding, are we talking about the same thing (the the minimize button in the following picture on the left)?
![Minimize Button?](https://user-images.githubusercontent.com/81589530/114273739-9a646f80-9a1b-11eb-9e66-e5067e05e3b0.png)

This change is essential, so I can't just remove it.



**For debugging purposes,** if you have the time of course, I'd ask you two things:
1. Launch a fresh profile under `about:profiles`, do not change any settings or themes and try _only photon-tabs.css_
- if you still experience the issue, continue to step 2
- if it stops happening, try finding the customization that causes it

2.  please try out this style instead too. This should narrow down whether the cause is the variable being used somewhere else.
```css
.tab-background {
    margin-block: 0 !important;
}
```

Also try to provide as much information as possible.

**Comment by hatran777** [comment]
Actually, my bad for bothering you. I should've tested it more cause it appears to only be affecting this one profile. I copied my same exact chrome folder into a different profile and it seems to work just fine on the new profile. I'll poke around this some more. Thanks for the help. 
![image](https://user-images.githubusercontent.com/54563292/114278699-daa8fb00-99e5-11eb-8023-cdffb53c7c4e.png)

**Comment by hatran777** [comment]
Yea, I guess I just been defaulting the compact design under the customization settings, and only under touch density that the minimize button shows up.
